/**
 * Transactional email HTML + plain text for website enquiries.
 * Table-based layout for broad client support; inline styles only.
 */

const COPPER = "#b8651f"
const INK = "#1c1917"
const MUTED = "#57534e"
const WARM_BG = "#faf8f5"
const PAGE_BG = "#ebe8e4"

export type SubmissionContext = {
  formLabel: string
  pagePath: string
  pageUrl: string
  submittedAtFormatted: string
}

export type AdminDataRow = {
  label: string
  valueText: string
  valueHtml: string
}

export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;")
}

export function formatMelbourneTimestamp(d: Date): string {
  return new Intl.DateTimeFormat("en-AU", {
    timeZone: "Australia/Melbourne",
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  }).format(d)
}

function adminOuterTable(inner: string): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:${PAGE_BG};">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:${PAGE_BG};">
  <tr>
    <td align="center" style="padding:36px 16px;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e7e5e4;">
        ${inner}
      </table>
      <p style="margin:24px 0 0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:11px;color:${MUTED};line-height:1.5;max-width:640px;">
        Boutique Coffee · Melbourne workplace coffee machine rental<br/>
        This notification was generated by your website enquiry form.
      </p>
    </td>
  </tr>
</table>
</body>
</html>`.trim()
}

export function buildAdminNotificationHtml(
  ctx: SubmissionContext,
  rows: AdminDataRow[],
  headline: string,
): string {
  const rowHtml = rows
    .map(
      (r) => `
        <tr>
          <td style="padding:14px 20px;border-bottom:1px solid #f5f5f4;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:14px;color:${MUTED};width:34%;vertical-align:top;">${escapeHtml(r.label)}</td>
          <td style="padding:14px 20px;border-bottom:1px solid #f5f5f4;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:14px;color:${INK};vertical-align:top;font-weight:500;">${r.valueHtml}</td>
        </tr>`,
    )
    .join("")

  const inner = `
        <tr>
          <td style="background:linear-gradient(135deg,${INK} 0%,#292524 100%);padding:28px 32px;border-bottom:4px solid ${COPPER};">
            <p style="margin:0 0 8px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:11px;letter-spacing:0.12em;text-transform:uppercase;color:#a8a29e;">New enquiry</p>
            <p style="margin:0;font-family:Georgia,'Times New Roman',serif;font-size:26px;line-height:1.2;color:#fafaf9;font-weight:400;">${escapeHtml(headline)}</p>
          </td>
        </tr>
        <tr>
          <td style="padding:28px 32px 8px;background:${WARM_BG};border-bottom:1px solid #e7e5e4;">
            <p style="margin:0 0 6px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:10px;letter-spacing:0.14em;text-transform:uppercase;color:${COPPER};font-weight:600;">Submission source</p>
            <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:12px;">
              <tr>
                <td style="padding:10px 14px;background:#ffffff;border-radius:10px;border:1px solid #e7e5e4;">
                  <p style="margin:0 0 6px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:13px;color:${MUTED};"><strong style="color:${INK};">Form</strong> · ${escapeHtml(ctx.formLabel)}</p>
                  <p style="margin:0 0 6px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:13px;color:${MUTED};"><strong style="color:${INK};">Page path</strong> · <code style="background:#f5f5f4;padding:2px 8px;border-radius:4px;font-size:12px;color:${INK};">${escapeHtml(ctx.pagePath)}</code></p>
                  <p style="margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:13px;color:${MUTED};"><strong style="color:${INK};">Open page</strong> · <a href="${escapeHtml(ctx.pageUrl)}" style="color:${COPPER};font-weight:600;text-decoration:none;">${escapeHtml(ctx.pageUrl)}</a></p>
                  <p style="margin:10px 0 0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:12px;color:#a8a29e;">Received ${escapeHtml(ctx.submittedAtFormatted)} (Melbourne time)</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td style="padding:8px 0 32px;">
            <p style="margin:20px 32px 12px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:10px;letter-spacing:0.14em;text-transform:uppercase;color:${COPPER};font-weight:600;">Submitted details</p>
            <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-top:1px solid #e7e5e4;">
              ${rowHtml}
            </table>
          </td>
        </tr>`

  return adminOuterTable(inner)
}

export function buildAdminNotificationText(
  ctx: SubmissionContext,
  rows: AdminDataRow[],
  headline: string,
): string {
  return [
    headline,
    "",
    "SUBMISSION SOURCE",
    `Form: ${ctx.formLabel}`,
    `Page: ${ctx.pagePath}`,
    `URL: ${ctx.pageUrl}`,
    `When: ${ctx.submittedAtFormatted} (Melbourne)`,
    "",
    "DETAILS",
    ...rows.map((r) => `${r.label}: ${r.valueText}`),
  ].join("\n")
}

function userOuterTable(inner: string): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:${PAGE_BG};">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:${PAGE_BG};">
  <tr>
    <td align="center" style="padding:36px 16px;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;background:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e7e5e4;">
        ${inner}
      </table>
    </td>
  </tr>
</table>
</body>
</html>`.trim()
}

export function buildUserConfirmationHtml(args: {
  greetingName: string
  formLabel: string
  isConsult: boolean
}): string {
  const { greetingName, formLabel, isConsult } = args
  const hi = greetingName ? `Hi ${escapeHtml(greetingName)},` : "Hi there,"

  const bodyCopy = isConsult
    ? `Thank you for requesting a <strong>10-minute consult</strong> with Chris. Your details are with us and Chris will respond personally within <strong>one business day</strong> to book a time or answer quick questions.`
    : `Thank you for your interest in <strong>Boutique Coffee</strong>. We&apos;ve received your enquiry from the <strong>${escapeHtml(formLabel)}</strong> form. Chris will be in touch within <strong>one business day</strong> to confirm next steps.`

  const inner = `
        <tr>
          <td style="background:linear-gradient(135deg,${INK} 0%,#44403c 100%);padding:36px 40px;text-align:center;border-bottom:4px solid ${COPPER};">
            <p style="margin:0;font-family:Georgia,'Times New Roman',serif;font-size:28px;line-height:1.2;color:#fafaf9;letter-spacing:0.02em;">Boutique Coffee</p>
            <p style="margin:10px 0 0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:13px;color:#d6d3d1;font-weight:400;">Melbourne workplace coffee machine rental</p>
          </td>
        </tr>
        <tr>
          <td style="padding:40px 40px 32px;">
            <p style="margin:0 0 20px;font-family:Georgia,'Times New Roman',serif;font-size:22px;line-height:1.35;color:${INK};">${hi}</p>
            <p style="margin:0 0 20px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:16px;line-height:1.65;color:${MUTED};">${bodyCopy}</p>
            <table role="presentation" cellspacing="0" cellpadding="0" style="margin:28px 0;background:${WARM_BG};border-radius:12px;border:1px solid #e7e5e4;">
              <tr>
                <td style="padding:22px 24px;">
                  <p style="margin:0 0 8px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:12px;letter-spacing:0.08em;text-transform:uppercase;color:${COPPER};font-weight:600;">Prefer to talk now?</p>
                  <p style="margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:16px;">
                    <a href="tel:0411876625" style="color:${COPPER};font-weight:700;text-decoration:none;">0411 876 625</a>
                    <span style="color:${MUTED};"> · Chris, founder</span>
                  </p>
                </td>
              </tr>
            </table>
            <p style="margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:14px;line-height:1.6;color:${MUTED};">
              We&apos;re a small Melbourne team — no call centres, no runaround. Looking forward to speaking with you.
            </p>
          </td>
        </tr>
        <tr>
          <td style="padding:24px 40px 32px;background:#fafaf9;border-top:1px solid #e7e5e4;">
            <p style="margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:12px;line-height:1.6;color:#a8a29e;text-align:center;">
              This email confirms we received your enquiry.<br/>
              Please do not reply to this automated message — Chris will email or call you directly.
            </p>
          </td>
        </tr>`

  return userOuterTable(inner)
}

export function buildUserConfirmationText(args: {
  greetingName: string
  formLabel: string
  isConsult: boolean
}): string {
  const { greetingName, formLabel, isConsult } = args
  const hi = greetingName ? `Hi ${greetingName},` : "Hi there,"
  const mid = isConsult
    ? "Thank you for requesting a 10-minute consult with Chris. He will respond within one business day."
    : `Thank you for your interest in Boutique Coffee. We've received your enquiry from the "${formLabel}" form. Chris will be in touch within one business day.`
  return [
    hi,
    "",
    mid,
    "",
    "Prefer to talk now? Call Chris: 0411 876 625",
    "",
    "— Boutique Coffee · Melbourne",
  ].join("\n")
}

export function mailtoLink(email: string, label: string): string {
  return `<a href="mailto:${escapeHtml(email)}" style="color:${COPPER};font-weight:600;text-decoration:none;">${escapeHtml(label)}</a>`
}

export function telLink(phone: string, label: string): string {
  const tel = phone.replace(/\s+/g, "")
  return `<a href="tel:${escapeHtml(tel)}" style="color:${COPPER};font-weight:600;text-decoration:none;">${escapeHtml(label)}</a>`
}
